services:
  django:
    build: .
    container_name: kpi_tracker
    command: gunicorn --workers 4 -b 0.0.0.0:3000 --timeout 600 enterprise_kpi_tracker.wsgi:application
    ports:
      - ":3000"
    labels:
      - "traefik.http.routers.static.rule=PathPrefix(`/static`)"
      - "traefik.http.routers.static.service=static"
      - "traefik.http.services.static.loadbalancer.server.port=443"
      - "traefik.http.routers.static.entrypoints=web"

    restart: always
